services:
  customer-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer-service
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      EXTERNAL_API_BASE_URL: https://jsonplaceholder.typicode.com
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    restart: unless-stopped
