spring:
  application:
    name: customer-manager

  autoconfigure:
    exclude:
      - org.springframework.boot.micrometer.metrics.autoconfigure.system.SystemMetricsAutoConfiguration

  datasource:
    url: jdbc:h2:mem:customerdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}

  http:
    client:
      connect-timeout: 5s
      read-timeout: 10s

profiles:
  admin:
    password: ${ADMIN_PASSWORD}
  user:
    password: ${USER_PASSWORD}

score-api:
  base-url: ${SCORE_SERVICE_BASE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    com.jadno.datum.ClientManager: DEBUG